/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SavedSessionsRouteImport } from './routes/saved-sessions'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as GameiqRouteImport } from './routes/gameiq'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionDetailSessionIdRouteImport } from './routes/session-detail.$sessionId'
import { Route as DrillDetailDrillIdRouteImport } from './routes/drill-detail.$drillId'
import { Route as CoachSessionIdRouteImport } from './routes/coach.$sessionId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSessionsRoute = SavedSessionsRouteImport.update({
  id: '/saved-sessions',
  path: '/saved-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const GameiqRoute = GameiqRouteImport.update({
  id: '/gameiq',
  path: '/gameiq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDetailSessionIdRoute = SessionDetailSessionIdRouteImport.update({
  id: '/session-detail/$sessionId',
  path: '/session-detail/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillDetailDrillIdRoute = DrillDetailDrillIdRouteImport.update({
  id: '/drill-detail/$drillId',
  path: '/drill-detail/$drillId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSessionIdRoute = CoachSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRouteWithChildren
  '/drills': typeof DrillsRoute
  '/favourites': typeof FavouritesRoute
  '/gameiq': typeof GameiqRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/saved-sessions': typeof SavedSessionsRoute
  '/sessions': typeof SessionsRoute
  '/team': typeof TeamRoute
  '/coach/$sessionId': typeof CoachSessionIdRoute
  '/drill-detail/$drillId': typeof DrillDetailDrillIdRoute
  '/session-detail/$sessionId': typeof SessionDetailSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRouteWithChildren
  '/drills': typeof DrillsRoute
  '/favourites': typeof FavouritesRoute
  '/gameiq': typeof GameiqRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/saved-sessions': typeof SavedSessionsRoute
  '/sessions': typeof SessionsRoute
  '/team': typeof TeamRoute
  '/coach/$sessionId': typeof CoachSessionIdRoute
  '/drill-detail/$drillId': typeof DrillDetailDrillIdRoute
  '/session-detail/$sessionId': typeof SessionDetailSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRouteWithChildren
  '/drills': typeof DrillsRoute
  '/favourites': typeof FavouritesRoute
  '/gameiq': typeof GameiqRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/saved-sessions': typeof SavedSessionsRoute
  '/sessions': typeof SessionsRoute
  '/team': typeof TeamRoute
  '/coach/$sessionId': typeof CoachSessionIdRoute
  '/drill-detail/$drillId': typeof DrillDetailDrillIdRoute
  '/session-detail/$sessionId': typeof SessionDetailSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/calendar'
    | '/coach'
    | '/drills'
    | '/favourites'
    | '/gameiq'
    | '/membership'
    | '/profile'
    | '/programs'
    | '/progress'
    | '/saved-sessions'
    | '/sessions'
    | '/team'
    | '/coach/$sessionId'
    | '/drill-detail/$drillId'
    | '/session-detail/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/calendar'
    | '/coach'
    | '/drills'
    | '/favourites'
    | '/gameiq'
    | '/membership'
    | '/profile'
    | '/programs'
    | '/progress'
    | '/saved-sessions'
    | '/sessions'
    | '/team'
    | '/coach/$sessionId'
    | '/drill-detail/$drillId'
    | '/session-detail/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/calendar'
    | '/coach'
    | '/drills'
    | '/favourites'
    | '/gameiq'
    | '/membership'
    | '/profile'
    | '/programs'
    | '/progress'
    | '/saved-sessions'
    | '/sessions'
    | '/team'
    | '/coach/$sessionId'
    | '/drill-detail/$drillId'
    | '/session-detail/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRouteWithChildren
  DrillsRoute: typeof DrillsRoute
  FavouritesRoute: typeof FavouritesRoute
  GameiqRoute: typeof GameiqRoute
  MembershipRoute: typeof MembershipRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  SavedSessionsRoute: typeof SavedSessionsRoute
  SessionsRoute: typeof SessionsRoute
  TeamRoute: typeof TeamRoute
  DrillDetailDrillIdRoute: typeof DrillDetailDrillIdRoute
  SessionDetailSessionIdRoute: typeof SessionDetailSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-sessions': {
      id: '/saved-sessions'
      path: '/saved-sessions'
      fullPath: '/saved-sessions'
      preLoaderRoute: typeof SavedSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameiq': {
      id: '/gameiq'
      path: '/gameiq'
      fullPath: '/gameiq'
      preLoaderRoute: typeof GameiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-detail/$sessionId': {
      id: '/session-detail/$sessionId'
      path: '/session-detail/$sessionId'
      fullPath: '/session-detail/$sessionId'
      preLoaderRoute: typeof SessionDetailSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill-detail/$drillId': {
      id: '/drill-detail/$drillId'
      path: '/drill-detail/$drillId'
      fullPath: '/drill-detail/$drillId'
      preLoaderRoute: typeof DrillDetailDrillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$sessionId': {
      id: '/coach/$sessionId'
      path: '/$sessionId'
      fullPath: '/coach/$sessionId'
      preLoaderRoute: typeof CoachSessionIdRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface CoachRouteChildren {
  CoachSessionIdRoute: typeof CoachSessionIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachSessionIdRoute: CoachSessionIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRouteWithChildren,
  DrillsRoute: DrillsRoute,
  FavouritesRoute: FavouritesRoute,
  GameiqRoute: GameiqRoute,
  MembershipRoute: MembershipRoute,
  ProfileRoute: ProfileRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  SavedSessionsRoute: SavedSessionsRoute,
  SessionsRoute: SessionsRoute,
  TeamRoute: TeamRoute,
  DrillDetailDrillIdRoute: DrillDetailDrillIdRoute,
  SessionDetailSessionIdRoute: SessionDetailSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
